runtime: python39
entrypoint: gunicorn -b :$PORT "flaskr:create_app()"

env_variables:
    DB_USER: postgres
    DB_PASSWORD: password
    DB_SQL_CONNECTION_NAME: driver-management-328507:asia-southeast2:driver-timesheet
    DB_NAME: driver-management
    PYTHONDONTWRITEBYTECODE: 1
