runtime: python
env: flex
entrypoint: gunicorn -b :$PORT "flaskr:create_app()"

runtime_config:
    python_version: 3

env_variables:
    FLASK_APP: "flaskr"
    DB_USER: "postgres"
    DB_PASSWORD: "password"
    DB_SQL_CONNECTION_NAME: "driver-management-328507:asia-southeast2:driver-timesheet"
    DB_NAME: "driver-management"
    PYTHONDONTWRITEBYTECODE: 1
